Repository six-bald-heads/Six_Bald_Heads_Frontend, pull requests merged in 2023-10, with the labels that each got.

#10 [Feat] 코드 에디터 병합
  package-lock.json
  package.json
  src/components/CodeEditor.tsx
  src/pages/MainPage.tsx
Labels: 전지희, 프론트엔드_구현

#18 [Feat] 파일트리 컴포넌트 병합
  .gitignore
  package-lock.json
  package.json
  src/components/CodeEditor.tsx
  src/components/FileDirectory.tsx
  src/components/Filedirectory/FileDirectory.tsx
  src/components/Filedirectory/RightClickMenu.tsx
  src/components/Filedirectory/api.ts
  src/components/Filedirectory/styles/FileDirectoryStyles.ts
  src/components/Filedirectory/treeHelpers.tsx
  src/pages/MainPage.tsx
Labels: 최진영, 프론트엔드_구현

#12 [Feat] 회원가입/로그인 병합
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/assets/bg-login.jpeg
  src/assets/logo-fill.png
  src/assets/logo.png
  src/assets/react.svg
  src/components/FindPasswordModal.tsx
  src/components/PrivateRoute.tsx
  src/context/AuthProvider.tsx
  src/hooks/useAuth.ts
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  vite.config.ts
Labels: 전지희, 프론트엔드_구현

#17 [Feat] 스낵바 컴포넌트 병합
  src/App.tsx
  src/components/Snackbar/Error.tsx
  src/components/Snackbar/Info.tsx
  src/components/Snackbar/Success.tsx
  src/components/Snackbar/Warning.tsx
  src/pages/SnackbarPage.tsx
Labels: 전지희, 프론트엔드_구현, 해보고싶어요!

#21 New tree
  .gitignore
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/assets/bg-login.jpeg
  src/assets/logo-fill.png
  src/assets/logo.png
  src/assets/react.svg
  src/components/CodeEditor.tsx
  src/components/Filedirectory/FileDirectory.tsx
  src/components/Filedirectory/RightClickMenu.tsx
  src/components/Filedirectory/TreeFile.tsx
  src/components/Filedirectory/styles/DirectoryStyle.ts
  src/components/Filedirectory/treeHelpers.tsx
  src/components/FindPasswordModal.tsx
  src/components/PrivateRoute.tsx
  src/components/Snackbar/Error.tsx
  src/components/Snackbar/Info.tsx
  src/components/Snackbar/Success.tsx
  src/components/Snackbar/Warning.tsx
  src/components/api/fileApi.ts
  src/components/api/index.ts
  src/context/AuthProvider.tsx
  src/hooks/useAuth.ts
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignupPage.tsx
  src/pages/SnackbarPage.tsx
  vite.config.ts
Labels: 최진영, 프론트엔드_구현

#20 [Feat] 프로필 컴포넌트 병합
  package.json
  src/App.tsx
  src/assets/logo-square.png
  src/components/CodeEditor.tsx
  src/components/DeleteAccountModal.tsx
  src/components/Filedirectory/api.ts
  src/components/FindPasswordModal.tsx
  src/components/ProfileModal.tsx
  src/components/Snackbar/Error.tsx
  src/components/Snackbar/Info.tsx
  src/components/Snackbar/Success.tsx
  src/components/Snackbar/Warning.tsx
  src/context/AuthProvider.tsx
  src/context/SnackbarContext.tsx
  src/hooks/useSnackbar.ts
  src/pages/LoginPage.tsx
  src/pages/SignupPage.tsx
  src/pages/SnackbarPage.tsx
Labels: 전지희, 프론트엔드_구현

#22 New tree
  package-lock.json
  package.json
  src/components/CodeEditor.tsx
  src/components/Filedirectory/FileDirectory.tsx
  src/components/Filedirectory/RightClickMenu.tsx
  src/components/Filedirectory/TreeFile.tsx
  src/components/Filedirectory/api.ts
  src/components/Filedirectory/styles/DirectoryStyle.ts
  src/components/api/fileApi.ts
  src/components/api/index.ts
  src/pages/MainPage.tsx
Labels: 최진영, 프론트엔드_구현

#23 Feat jihee
  src/assets/bg-login.jpeg
  src/components/DeleteAccountModal.tsx
  src/components/ProfileModal.tsx
  src/context/AuthProvider.tsx
  src/pages/LoginPage.tsx
Labels: 리팩토링, 전지희, 프론트엔드_구현
